import { workspace } from "vscode";

export const getConfiguration = <T>(key: string) => {
  return workspace.getConfiguration("templagen").get<T>(key);
};

export const configGetDirTemplates = (): [] => {
  return getConfiguration<[]>("dirTemplates") ?? [];
};

export const configGetTemplatesFolderPath = (): string => {
  return getConfiguration<string>("templatesFolderPath") ?? "";
};

export const configGetFolderTemplateAutoGenerateDirs = (): boolean => {
  return getConfiguration<boolean>("folderTemplateAutoGenerateDirs") ?? false;
};

export const configGetListShowTemplatesGrouped = (): boolean => {
  return getConfiguration<boolean>("listShowTemplatesGrouped") ?? false;
};

export const configGetListNameSeparatedBy = (): string => {
  return getConfiguration<string>("listNameSeparatedBy") ?? " $-> ";
};

export const configGetListShowTemplateNameAsPath = (): boolean => {
  return getConfiguration<boolean>("listShowTemplateNameAsPath") ?? true;
};
